server.port=${PORT:8080}

# BFHL Configurable Parameters
# You can change these to match your actual details
bfhl.user.name=veer_vanshaj
bfhl.user.dob=18072005
bfhl.user.email=veer2320.be23@chitkara.edu.in
bfhl.user.roll-number=2310992320
